name: Code linter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  python-ruff:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: python-ruff-lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0

  mypy:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'
      - run: pip install -e ".[dev]"
      - run: mypy acp.py
