name: Code linter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  python-ruff:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: python-ruff-lint
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
