name: Markdown lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  markdown-lint:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: markdown-lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: pymarkdown
        run: |
          pip install pymarkdownlnt==0.9.37 --quiet
          find . -name "*.md" -not -path "./venv/*" -print0 | xargs -0 pymarkdown --config .pymarkdown.json scan
