name: Markdown lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  markdown-lint:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: markdown-lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: pymarkdown
        run: |
          pip install pymarkdownlnt==0.9.37 --quiet
          find . -name "*.md" -not -path "./venv/*" -print0 | xargs -0 pymarkdown --config .pymarkdown.json scan
