name: Validate pyproject config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-pyproject:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    name: validate-pyproject
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install validate-pyproject
        run: pip install "validate-pyproject[all]"

      - name: Validate pyproject.toml
        run: validate-pyproject pyproject.toml
